### ISSUE TITLE
Move "view all" button for widget areas next to title, rather than below posts.

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-borderzine#32]
We'll need to estimate this first before proceeding. 

[Our Border Life landing page.pdf](https://github.com/INN/umbrella-borderzine/files/3650046/Our.Border.Life.landing.page.pdf)

**Comment by benlk** [comment]
The wireframe shows that we're doing this for the following widgets:
- Photo Galleries (probably a recent posts widget, with headlines overlaid on the images)
- Latest Podcasts (probably a recent posts widget, without thumbnails)
- Audio Conversations (probably a recent posts widget)
- Radio Stories (Probably a recent posts widget) 

The "Our Stories" widget looks the same as the "Audio Conversations" and "Radio Stories" widgets but doesn't have this link at all. Because it doesn't have the link, we don't need to worry about placement of the link on this widget, and so this widget can be affected by the changes made to the other widgets without harm. 


🤔 Although, if they don't want to rearrange this page post-publication, we *could* just hardcode everything's position on the page....

**Comment by benlk** [comment]
![Screen Shot 2019-09-25 at 14 04 23 ](https://user-images.githubusercontent.com/1754187/65627927-6000c200-df9e-11e9-84c2-fcbe19243b73.png)

Now numbered for reference.

We're probably going to end up creating/modifying three morphs/variants of the "recent posts" widget for this project:
- `5`: a multiple of 5 posts in a 5-column layout, showing the headlines only.
- `3`: a multiple of 3 posts in a 3-column layout, showing headline and thumbnail.
-  `img`: a multiple of 6 posts in a 3-column layout, showing headline overlaid on thumbnail if possible, and if not then headline below thumbnail.

In the above illustration, widgets 1 and 4 are complicated by the presence of "sidebar" content in the widget. It may not be a good idea to have those present as widgets, but that breaks up the idea of having this page be one single list of widgets into a hardcoded section, a widget area, a hardcoded section, and a widget area.

**Comment by benlk** [comment]
Affects:

- #36 
- #33 
- #45

**Comment by MirandaEcho** [comment]
Closing, because it is included in the individual sections.
